#!/usr/bin/env bash

# Define the menu options
chosen=$(printf "   Power Off\n Restart\n   Suspend\n Log out" | rofi -dmenu -i -l 4)

case "$chosen" in
    "   Power Off")
        sudo shutdown -p now ;;  # FreeBSD uses -p to power off
    " Restart")
        sudo reboot ;;
    "   Suspend")
        sudo zzz ;;               # Native FreeBSD command for Suspend-to-RAM
    " Log out")
        i3-msg exit ;;
    *)
        exit 1 ;;
esac
