# Default wallpaper configuration

wallpaper {
    monitor = eDP-2
    path = ~/.dotfiles/wallpapers/xgui4-os/HyprArch.png
    fit_mode = fill
}

wallpaper {
    monitor = eDP-1
    path = ~/.dotfiles/wallpapers/xgui4-os/HyprArch.png
    fit_mode = fill
}

wallpaper {
   monitor = HDMI-A-0
   path = ~/.dotfiles/wallapers/xgui4-os/HyprArch.png
   fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.dotfiles/wallpapers/xgui4-os/HyprArch.png
    fit_mode = fill
}

wallpaper {
    monitor = HDMI-A-2
    path = ~/.dotfiles/wallpapers/xgui4-os/HyprArch.png
    fit_mode = fill
}
