########################################################################################
# HyprArch 0.0.2
# By Xgui4
########################################################################################

################
### MONITORS ###
################

source = ~/.dotfiles/hyprland/.config/hypr/monitors.conf

###################
### MY PROGRAMS ###
###################

$terminal = kitty  # default terminal 
$fileManager = dolphin # default file manager
$browser = firefox # default browser
$menu = rofi # default launcher/menu 
$emoji = rofi -show emoji # default emoji picker
$clipboardManager = copyq # defaiut clipboard manager 
$screenshotUtiliy = flameshot gui # default screenshot utility

#################
### AUTOSTART ###
#################

source = ~/.config/hypr/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = ~/.config/hypr/env.conf

source = ~/.config/hypr/nvidia.conf 

#####################
### LOOK AND FEEL ###
#####################

source = ~/.config/hypr/appearence.conf

#############
### INPUT ###
#############  

source =  ~/.config/hypr/input.conf

################
## Permission ##
################

source = ~/.config/hypr/permission.conf

###################
### KEYBINDINGS ###
###################

source = ~/.config/hypr/keybinding.conf
bind =, PRINT, exec, $screenshotUtiliy

##############################
### WINDOWS AND WORKSPACES ###
##############################

source = ~/.config/hypr/windows-rule.conf

##################
## Fix for apps ##
##################

xwayland:force_zero_scaling = true

####################
## Plugins config ##
####################

# temporaly disabled until i found a solution 
# source = ~/.config/hypr/plugins.conf
