plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1
	    skip_empty = false
    }

    hyprbars {
        # example config
        bar_height = 20

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eeee11), 10, , hyprctl dispatch fullscreen 1

        # cmd to run on double click of the bar
        on_double_click = hyprctl dispatch fullscreen 1
    }
}

# See What Change
# # windows rule 
# windowrule { 
#     name = no-titlebar-for-tiled-windows
#     hyprbars:no_bar = true
#     match:float = false
# }

# keybindng 
bind = Super, TAB, exec, qs ipc -c overview call overview toggle
bind = alt, TAB, hyprexpo:expo, toggle

# input 
gesture = 3, vertical, dispatcher, hyprexpo:expo, toggle

