plugin {
    hyprbars {
        # example config
        bar_height = 20

        enabled = true

        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(ff4040), 10, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(eeee11), 10, , hyprctl dispatch fullscreen 1

        # cmd to run on double click of the bar
        on_double_click = hyprctl dispatch fullscreen 1
    }
}

# See What Change
# # windows rule 
windowrule { 
    name = no-titlebar-for-tiled-windows
    match:float = false
    hyprbars:no_bar = true
}

# keybindng 
bind = Super, TAB, exec, qs ipc -c overview call overview toggle

# input 
gesture = 3, vertical, dispatcher, hyprexpo:expo, toggle

